services:
    app1:
        build: ./doom
    app2:
        build: ./lionking
    app3:
        build: ./princeofpersia
    nginx:
        build: ./nginx
        ports:
            - 80:80
        depends_on:
            - app1
            - app2
            - app3

